litemall:
  # 开发者应该设置成自己的wx相关信息
  wx:
#********************************************************
#    #    以下是张相涛通过测试账号修改本地的记录
    app-id: wx55c19ad1356ff1fc
    app-secret: 9ef2974b99a5b6f79394dc4733eef835
#********************************************************
    #    #    以下是劲远科技的app-id及密钥
#    app-id: wx09852c68fba4b7bd
#    app-secret: 4dd71405d61d0750de78c7c1866880ae
    #********************************************************


#    #以下是支付信息
    mch-id: xxxxxxx
    mch-key: xxxxxxx
    notify-url: http://www.jinyuanbigdata.com:8000/wx/order/pay-notify
#*******************************************************************

    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: /opt/application/paimai/apiclient_cert.p12
  #开发者应该设置成自己的支付宝相关信息

  alipay:
    app-id: xxxxxx
    seller_id: xxxxxx
    rsa-private-key: xxxx
    #支付宝公钥
    alipay-public-key: xxxxx
    url: https://openapi.alipay.com/gateway.do
    notify-url: http://www.jinyuanbigdata.com:8000/wx/order/alipay-notify
    #同步通知地址
    return-url: http://www.jinyuanbigdata.com:8000/wx/order/ali-returnurl
    #跳转地址
    jump-url: http://paimaistore.jinyuanbigdata.com/pages/money/paySuccess
  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: false
      host: smtp.exmail.qq.com
      username: ex@ex.com.cn
      password: XXXXXXXXXXXXX
      sendfrom: ex@ex.com.cn
      sendto: ex@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      appid: 111111111
      appkey: xxxxxxxxxxxxxx
      template:
      - name: paySucceed
        templateId: 156349
      - name: captcha
        templateId: 156433
      - name: ship
        templateId: 158002
      - name: refund
        templateId: 159447

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: false
      template:
      - name: paySucceed
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: captcha
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: ship
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - name: refund
        templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # 快鸟物流查询配置
  express:
    enable: false
    appId: "XXXXXXXXX"
    appKey: "XXXXXXXXXXXXXXXXXXXXXXXXX"
    vendors:
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
#    active: aliyun
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      address: http:///www.jinyuanbigdata.com:8000/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: xxxxx
      accessKeySecret: xxxxx
      bucketName: xxxxx
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: litemall
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall
  # 对象存储配置
  pdf:
    #正式环境
    fontFilePath: /opt/application/paimai/msyh.ttf
    actlogo: /opt/application/paimai/ActLogo.jpg
    actQRCode: /opt/application/paimai/ActQRCode.jpg
#    #本地环境
#    fontFilePath: C:\Users\Administrator\Desktop\msyh.ttf
#    actlogo: C:\Users\Administrator\Desktop\ActLogo.jpg
#    actQRCode: C:\Users\Administrator\Desktop\ActQRCode.jpg
